### ISSUE TITLE
A few problems in Python 3.x

### ISSUE THREAD

**Issue by jfroejk** [KristianOellegaard/python-economic-rest#2]
python-economic-rest doesn't work out-of-the box in Python 3.x. I found a couple of issues. There may be more so I don't want to make a commit to the project.

1) query.py: urlparse is part of urllib in Python 3. Import as
try:
    import urllib.parse as urlparse
except ImportError:
    import urlparse

2) utils.py:economic_request(): r.content is a byte string, not a char string. Solution:
    if r.status_code == 200:
        content = str(r.content, 'utf-8')
        return json.loads(content)

regards,

Jørgen F Kjærsgaard

**Comment by ghost** [comment]
Snippets with syntax highlighting:

``` python
try:
    import urllib.parse as urlparse
except ImportError:
    import urlparse
```

and:
``` python
if r.status_code == 200:
    content = str(r.content, 'utf-8')
    return json.loads(content)
```

**Comment by ghost** [comment]
Hmm, on't the code with these changes be still python 2 and potentially python 3 compatible? Seems like a good step forward in that case.

**Comment by jfroejk** [comment]
The first change is 2 and 3 compatible.

The second issue is that r.content must be converted to unicode in Python 3
for json.loads() to work.

A possible though probably not particularly elegant solution is:

try:
    unicode
except NameError
    unicode = str  # unicode is str in Python 3+

and then

if r.status_code == 200:
    content = unicode(r.content, 'utf-8')
    return json.loads(content)



med venlig hilsen / regards

Jørgen Frøjk Kjærsgaard
*Systemudvikler*

www.metation.dk  T: 8625 0038  M: 2613 8038
Bjørnholms Allé 20,1 - DK-8260 Viby J


2017-06-15 14:16 GMT+02:00 Laust Rud Jacobsen <notifications@github.com>:

**Comment by hoerup** [comment]
since python2 is soon EOL, I think it makes sence just to update this library to python 3

**Comment by MatinF** [comment]
Any update on integrating this?

**Comment by hoerup** [comment]
Ping @KristianOellegaard

**Comment by alesdotio** [comment]
Sorry this took so long :( 0.9.0 now supports py3
